# docker-compose.yml

version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
